import 'dart:convert';
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';
import '../models/eye_screening_result.dart';
import '../models/user_profile.dart';
import 'firebase_service.dart';

class ExportService {
  final FirebaseService _firebaseService = FirebaseService();

  /// Generates PDF document bytes for a specific screening result
  Future<Uint8List> generateScreeningPdfBytes(EyeScreeningResult result, UserProfile? profile) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('VisionAI CLINICAL EYE REPORT', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
                      pw.Text('Intelligent EyeCare Screening System', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
                    ],
                  ),
                  pw.Text('DATE: ${result.date.day}/${result.date.month}/${result.date.year}', style: const pw.TextStyle(fontSize: 10)),
                ],
              ),
              pw.Divider(thickness: 1),
              pw.SizedBox(height: 12),

              // Patient Context
              pw.Text('PATIENT INFORMATION', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 6),
              pw.Text('Name: ${profile?.name ?? "Patient"}'),
              pw.Text('Age: ${profile?.age ?? "N/A"} years | Gender: ${profile?.gender ?? "N/A"}'),
              pw.SizedBox(height: 16),

              // Screening Result
              pw.Text('SCREENING FINDINGS', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 6),
              pw.Text('Primary Finding: ${result.observation}', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
              pw.Text('Severity Level: ${result.riskLevel.name.toUpperCase()} RISK'),
              pw.Text('AI Model Confidence: ${result.confidence.toStringAsFixed(1)}%'),
              pw.Text('Model Version: ${result.modelVersion}'),
              pw.SizedBox(height: 12),

              // Disease Explanation
              pw.Text('CLINICAL EXPLANATION', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 4),
              pw.Text(result.explanation.isNotEmpty ? result.explanation : 'No detailed explanation provided.'),
              pw.SizedBox(height: 16),

              // Recommendations
              pw.Text('RECOMMENDED NEXT STEPS', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 4),
              pw.Text('1. Present this report to a licensed eye specialist or ophthalmologist for professional confirmation.'),
              pw.Text('2. Keep this digital document saved in your personal health records.'),
              pw.SizedBox(height: 24),

              // Disclaimer
              pw.Divider(thickness: 0.5),
              pw.Text(
                'DISCLAIMER: This report is generated by VisionAI decision-support algorithm for preliminary screening purposes only. It is not a definitive medical diagnosis.',
                style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700),
              ),
            ],
          );
        },
      ),
    );

    return pdf.save();
  }

  /// Downloads & opens print dialog for screening PDF
  Future<void> printOrSavePdf(EyeScreeningResult result, UserProfile? profile) async {
    final pdfBytes = await generateScreeningPdfBytes(result, profile);
    await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => pdfBytes);
  }

  /// Shares screening PDF via share_plus
  Future<void> shareScreeningPdf(EyeScreeningResult result, UserProfile? profile) async {
    final pdfBytes = await generateScreeningPdfBytes(result, profile);
    final directory = await getApplicationDocumentsDirectory();
    final file = File('${directory.path}/VisionAI_Report_${result.id}.pdf');
    await file.writeAsBytes(pdfBytes);

    await Share.shareXFiles(
      [XFile(file.path)],
      text: 'VisionAI Eye Screening Clinical Report - ${result.observation}',
    );
  }

  Future<void> exportDataAsJson() async {
    try {
      final user = _firebaseService.currentUser;
      if (user == null) throw Exception("User not authenticated");

      final data = {
        'user': {
          'uid': user.uid,
          'email': user.email,
        },
        'exportDate': DateTime.now().toIso8601String(),
      };

      final jsonString = jsonEncode(data);
      final directory = await getApplicationDocumentsDirectory();
      final file = File('${directory.path}/my_health_data.json');
      await file.writeAsString(jsonString);

      await Share.shareXFiles(
        [XFile(file.path)],
        text: 'My EyeCare AI Health Data',
      );
    } catch (e) {
      debugPrint('Error exporting JSON: $e');
      rethrow;
    }
  }

  Future<void> exportDataAsPdf() async {
    try {
      final user = _firebaseService.currentUser;
      if (user == null) throw Exception("User not authenticated");

      final pdf = pw.Document();
      pdf.addPage(
        pw.Page(
          build: (pw.Context context) {
            return pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('EyeCare AI Health Data Report', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 20),
                pw.Text('User ID: ${user.uid}'),
                pw.Text('Email: ${user.email ?? "No Email"}'),
                pw.Text('Export Date: ${DateTime.now().toString()}'),
              ],
            );
          },
        ),
      );

      final directory = await getApplicationDocumentsDirectory();
      final file = File('${directory.path}/my_health_data_report.pdf');
      await file.writeAsBytes(await pdf.save());

      await Share.shareXFiles(
        [XFile(file.path)],
        text: 'My EyeCare AI Health Report',
      );
    } catch (e) {
      debugPrint('Error exporting PDF: $e');
      rethrow;
    }
  }
}
