// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB80euTWA-ltZY341sP83soTCZQ3iD6g1o',
    appId: '1:62435551976:web:1ec8165e94288a035f775d',
    messagingSenderId: '62435551976',
    projectId: 'final-year-project-7e02d',
    authDomain: 'final-year-project-7e02d.firebaseapp.com',
    storageBucket: 'final-year-project-7e02d.firebasestorage.app',
    measurementId: 'G-QH9JKENXEN',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDxTLH41r5zmzjZN5aFjH_XLaK7kdK0OA',
    appId: '1:62435551976:ios:a382f25adb6998c55f775d',
    messagingSenderId: '62435551976',
    projectId: 'final-year-project-7e02d',
    storageBucket: 'final-year-project-7e02d.firebasestorage.app',
    iosBundleId: 'com.example.fypFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDxTLH41r5zmzjZN5aFjH_XLaK7kdK0OA',
    appId: '1:62435551976:ios:a382f25adb6998c55f775d',
    messagingSenderId: '62435551976',
    projectId: 'final-year-project-7e02d',
    storageBucket: 'final-year-project-7e02d.firebasestorage.app',
    iosBundleId: 'com.example.fypFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB80euTWA-ltZY341sP83soTCZQ3iD6g1o',
    appId: '1:62435551976:web:5c390e981e603d0b5f775d',
    messagingSenderId: '62435551976',
    projectId: 'final-year-project-7e02d',
    authDomain: 'final-year-project-7e02d.firebaseapp.com',
    storageBucket: 'final-year-project-7e02d.firebasestorage.app',
    measurementId: 'G-60DNLC67EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZHY_VgR_E99ZUPkVXmGCscAYWZ2eWQ-0',
    appId: '1:62435551976:android:8104a27b922633635f775d',
    messagingSenderId: '62435551976',
    projectId: 'final-year-project-7e02d',
    storageBucket: 'final-year-project-7e02d.firebasestorage.app',
  );
}
